name: Cypress Tests
on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false  # Continue running other machines even if one fails
      matrix:
        containers: [1, 2, 3]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        uses: cypress-io/github-action@v5
        with:
          record: true
          parallel: true
          group: 'Parallel Tests'
          ci-build-id: ${{ github.sha }}-${{ github.workflow }}-${{ github.event_name }}
          command: npx cypress run --record --parallel --browser chrome
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # Split tests based on spec files
          CYPRESS_GROUP: ${{ strategy.job-index }}
          CYPRESS_GROUP_COUNT: ${{ strategy.job-total }}